### ISSUE TITLE
Thêm danh mục sản phẩm

### ISSUE THREAD

**Issue by VoHoangSanh** [VoHoangSanh/CNPMNC#5]

**Comment by anhkhoi2011** [comment]
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới danh mục</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Danh mục</a></li>
                    <li class="breadcrumb-item active">Thêm mới</li>
                </ol>
            </div>
        </div>
    </div><
</section>


<section class="content">

    
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin thêm mới danh mục</h3>

            <div class="card-tools">

            </div>
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Add", "Category", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

                    
                    <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tên danh mục</label>
                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Tên danh mục" })
                            @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Mô tả</label>
                            @Html.TextAreaFor(x => x.Description, new { @class = "form-control", @placeholder = "Mô tả" })
                        </div>
                        <div class="form-group">
                            <label>Thứ tự</label>
                            @Html.TextBoxFor(x => x.Position, new { @class = "form-control", @Value = "1" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Seo title</label>
                            @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control", @placeholder = "Seo title" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Seo Desc</label>
                            @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control", @placeholder = "Seo Desc" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">SeoKeywords</label>
                            @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control", @placeholder = "SeoKeywords" })
                        </div>

                        <div class="form-group">
                            <a href="/admin/category" class="btn btn-primary">Quay lại</a>
                            <button type="submit" class="btn btn-danger">Submit</button>
                        </div>

                    </div>

                }
            </div>



        </div>
        
        <div class="card-footer">

        </div>
        
    </div>
